[package]
name = "squad_codegen"
version = "0.1.0"
authors = ["kezenator <github@kezenator.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies.syn]
version = "1.0.5"
features = ["full"]

[dependencies.quote]
version = "1.0.2"

[dependencies.proc-macro2]
version = "1.0.5"
